language: cpp
compiler:
  - clang++
  - gcc
os:
  - linux
  - osx
env:
  - 
before_install:
  - echo $LANG
  - echo $LC_ALL
  - cmake --version
  - ls -la
script:
  - ci/build_cmake.sh
notifications:
  slack:
    rooms:
      - secure: "eU6n0+Mx8zXV7ZOHWkIwjLNvjID3E6axxm03FbqcWQuC/HTSTjc8HjG9KExafhKh/cPZlpXO3PmIJH4r2n+fVTR4jxVW4PblocPmvcaWa4p+K4s17ZV9Wvy+RIl5YaWff9tc2j4vToZJkUyIDeuxLytlwV8n4AWaNqv986TlTfKaS6j/vA8zxwb3XvA2vt+6QF2yWAH5BMgCSfupZ/wkrPN4XfMVthbB82D8K8a8EvRCpe/HtyUwi936gvGVnYaZ3KoOzzJX/oIM/7JPc1tum1eteoFErYxrfP8FcgFJSu1UDG9nmi/d/Ou8Bv3VyfNU7Kd99J++EQDdd4bZ9Ze/R9Mo4CPAhz0tK1nEJbJM3tdY1WD9SI2Avs6bJlM8qHnHGHBJekr9SW6XQmBo4wGDfGtdKWWVoyL9y15G/p9hh2xF+AvRAAZ1N+j7WS6YOabuxnR9I/P14rhnZh1S4abiKtgWSeGfb4a2V60+abjlnKFPD6s24eEElo7zN6eoAgEei46AnnhIpixDtP2c6fZlTa346hbYsxoPfLy60IUJtD8yGNQI4qeTNdS2RHsQa3RCy+PFKuUsGvRUDoCDCXKw3lf4gExuO20OskDetbt2ngqFqq1FElxoyzy7ReEAyoWFLtJnYfdfJid87ffDLo9PvpxCcY2hKBoDHhHYzfyOt4w="

